<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-IIOPE3V" failures="1" tests="8" name="test.java.Func_02_Home_Middle" time="131.118" errors="0" timestamp="2022-07-13T00:59:17 KST" skipped="0">
  <testcase classname="test.java.Func_02_Home_Middle" name="Home_004_Middle_MyBlock_Star" time="2.060"/>
  <system-out/>
  <testcase classname="test.java.Func_02_Home_Middle" name="Home_007_Middle_Join_Block" time="7.321"/>
  <system-out/>
  <testcase classname="test.java.Func_02_Home_Middle" name="Home_001_Middle_Banner_Logout" time="77.105"/>
  <system-out/>
  <testcase classname="test.java.Func_02_Home_Middle" name="Home_002_Middle_Banner_Top" time="17.742"/>
  <system-out/>
  <testcase classname="test.java.Func_02_Home_Middle" name="Home_008_Middle_LineBanner" time="6.234">
    <failure message="expected [https://2ndblock.com/space#100] but found [https://2ndblock.com/room/ZTVqoyjWpAfjpjCZaUVD]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://2ndblock.com/space#100] but found [https://2ndblock.com/room/ZTVqoyjWpAfjpjCZaUVD]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at main.java.Common.Assert_CheckCurrentUrl(Common.java:162)
at test.java.Func_02_Home_Middle.Home_008_Middle_LineBanner(Func_02_Home_Middle.java:129)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Home_008_Middle_LineBanner -->
  <system-out/>
  <testcase classname="test.java.Func_02_Home_Middle" name="Home_006_Middle_Make_Block" time="7.160"/>
  <system-out/>
  <testcase classname="test.java.Func_02_Home_Middle" name="Home_005_Middle_MyBlock_Enter" time="7.284"/>
  <system-out/>
  <testcase classname="test.java.Func_02_Home_Middle" name="Home_003_Middle_OwnBlock_Info" time="6.212"/>
  <system-out/>
</testsuite> <!-- test.java.Func_02_Home_Middle -->
